name: OctoBell
options:
  bundleIdPrefix: com.zigastrgar.octobell
  minimumXcodeGenVersion: 2.18.0
targets:
  OctoBell:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      CURRENT_PROJECT_VERSION: "1"
      ENABLE_HARDENED_RUNTIME: YES
    sources:
      - path: Sources
    info:
      path: Info.plist
      properties:
        LSUIElement: true
        NSPrincipalClass: NSApplication
        CFBundleShortVersionString: "0.4.0" # x-release-please-version
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleIconName: AppIcon
        CFBundleIconFile: AppIcon
