blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/zigastrgar/octobell/discussions
    about: Have a question or want to discuss something that isn't a bug or feature request? Start a discussion!
